In [1]:
import numpy

In [22]:
a =numpy.array([[[[1,2,3],[4,5,6],[5,7,8]],[[12,3,34],[8,9,1],[6,43,5]]],[[[1,2,3],[4,5,6],[5,7,8]],[[12,3,34],[8,9,1],[6,43,5]]]],dtype='float64')
a

array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 5.,  7.,  8.]],

        [[12.,  3., 34.],
         [ 8.,  9.,  1.],
         [ 6., 43.,  5.]]],


       [[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 5.,  7.,  8.]],

        [[12.,  3., 34.],
         [ 8.,  9.,  1.],
         [ 6., 43.,  5.]]]])

In [33]:
a[0]

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 5.,  7.,  8.]],

       [[12.,  3., 34.],
        [ 8.,  9.,  1.],
        [ 6., 43.,  5.]]])

In [34]:
a[1]

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 5.,  7.,  8.]],

       [[12.,  3., 34.],
        [ 8.,  9.,  1.],
        [ 6., 43.,  5.]]])

In [31]:
a[0][0]

array([[1., 2., 3.],
       [4., 5., 6.],
       [5., 7., 8.]])

In [32]:
a[0][1]

array([[12.,  3., 34.],
       [ 8.,  9.,  1.],
       [ 6., 43.,  5.]])

In [35]:
a[1][0]

array([[1., 2., 3.],
       [4., 5., 6.],
       [5., 7., 8.]])

In [36]:
a[1][1]

array([[12.,  3., 34.],
       [ 8.,  9.,  1.],
       [ 6., 43.,  5.]])

In [23]:
a.dtype

dtype('float64')

In [24]:
a.itemsize

8

In [25]:
a

array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 5.,  7.,  8.]],

        [[12.,  3., 34.],
         [ 8.,  9.,  1.],
         [ 6., 43.,  5.]]],


       [[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 5.,  7.,  8.]],

        [[12.,  3., 34.],
         [ 8.,  9.,  1.],
         [ 6., 43.,  5.]]]])

In [28]:
a.data

In [15]:
a.ndim

4

In [17]:
b=numpy.array([[1,2,3],[3,4,5]])

In [18]:
b.shape

(2, 3)

In [19]:
b.size

6

In [16]:
a.shape

(2, 2, 3, 3)

In [20]:
a.size

36

In [37]:
c= numpy.array([[1,2,3],[4,5,6]])

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c[0]

array([1, 2, 3])

In [40]:
c[1]

array([4, 5, 6])

In [41]:
c[0][0]

1

In [42]:
c[0][1]

2

In [43]:
c[0][2]

3

In [44]:
c[1][0]

4

In [45]:
c[1][1]

5

In [46]:
c[1][2]

6

In [54]:
numpy.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
numpy.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
numpy.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
numpy.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [67]:
numpy.linspace(4,10,9)

array([ 4.  ,  4.75,  5.5 ,  6.25,  7.  ,  7.75,  8.5 ,  9.25, 10.  ])

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
b=np.ones((2,3),dtype='int32')

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
a+b

array([[2, 3, 4],
       [5, 6, 7]])

In [7]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
a * b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a @ b

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
b =b.reshape((3,2))

In [14]:
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
b.shape

(3, 2)

In [16]:
a.shape

(2, 3)

In [17]:
a @ b

array([[ 6,  6],
       [15, 15]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
a=np.array([[1,4],[5,9]])

In [24]:
a

array([[1, 4],
       [5, 9]])

In [25]:
np.linalg.inv(a)

array([[-0.81818182,  0.36363636],
       [ 0.45454545, -0.09090909]])

In [29]:
4/11

0.36363636363636365

In [28]:
9/11

0.8181818181818182

In [30]:
5/11

0.45454545454545453

In [31]:
1/11

0.09090909090909091

In [32]:
np.linalg.inv(a)

array([[-0.81818182,  0.36363636],
       [ 0.45454545, -0.09090909]])

In [33]:
a

array([[1, 4],
       [5, 9]])

In [35]:
b=np.ones((2,2),dtype ='int32')

In [36]:
b

array([[1, 1],
       [1, 1]])

In [38]:
np.vstack([a,b])

array([[1, 4],
       [5, 9],
       [1, 1],
       [1, 1]])

In [39]:
np.hstack([a,b])

array([[1, 4, 1, 1],
       [5, 9, 1, 1]])

In [40]:
np.column_stack([a,b])

array([[1, 4, 1, 1],
       [5, 9, 1, 1]])

In [41]:
np.row_stack([a,b])

array([[1, 4],
       [5, 9],
       [1, 1],
       [1, 1]])

In [44]:
np.min(a)

1

In [43]:
np.max(a)

9

In [42]:
np.sum(a)

19