#### module :-

--->> Any python file is a module  ( .py )

--->> Collections of function defination with in a python file


#### package:-

--->> It is a folder 

--->> Collection of modules  with in a folder 

##### Types of modules and packages

--->> 1. Pre defined Module and packages

        -->> whatever the modules and packages are already available with in python ide
        
        -->>  math ,  os, cmath, time , ctypes , socket, tkinter , threading 

--->> 2. Semi pre defined Module and packages

        -->> this are not defined inside of python
        
        -->> this are not defined by programmer
        
        -->> this all  are defined by some others , they are give the permission to install in your python ide
        
        -->> then we can use same like pre defined module and packages
        
        -->> numpy , pandas, matplotlib , sklear , open cv

--->> 3. User defined Module and packages

        -->> which are defined by programmer 
        
        -->> we can use only in your computer
        
#### importance of module and pacakges 

        -->> we can reduce the code size
        
        -->> we can reuse the code
        
##### how we can use these modules and pacakges 

        -->> import -->> we can import the modules and packages 

In [1]:
def factorial(num = 1):
    if(isinstance(num,int)):
        if(num>=0):
            fact =1
            for i in range(2,num+1):
                fact = fact * i
            else:
                return fact
        else:
            return None
    else:
        return None

n = input("enter n : ")
print factorial(n)

n = input("enter n : ")
print factorial(n)
n = input("enter n : ")
print factorial(n)

enter n : 45.55
None
enter n : -7
None
enter n : 5
120


In [3]:
import math
print dir(math)

['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']


In [1]:
import math
help(math.sin)

Help on built-in function sin in module math:

sin(...)
    sin(x)
    
    Return the sine of x (measured in radians).



In [2]:
import math
help(math.factorial)

Help on built-in function factorial in module math:

factorial(...)
    factorial(x) -> Integral
    
    Find x!. Raise a ValueError if x is negative or non-integral.



In [1]:
import math
print math.sin(math.pi/2)# 1
print math.sin(0)# 0
print math.sin(math.pi/3) # math.sqrt(3)/2

print math.sin(math.pi/6)# 1/2
print math.sin(math.pi/4)# 1/ sqrt(2)


1.0
0.0
0.866025403784
0.5
0.707106781187


In [1]:
import math
n = input("enter n : ")
print math.factorial(n)


enter n : 5
120


In [8]:
import math
print math.ceil(12.01)
print math.floor(11.999)
print math.pow(12,3)
print math.log10(10)
print math.radians(180)
print math.degrees(math.pi)

13.0
11.0
1728.0
1.0
3.14159265359
180.0


In [14]:
import math  as m

print m.ceil(12.01)
print m.floor(11.999)
print m.pow(12,3)
print m.log10(10)
print m.radians(180)
print m.degrees(m.pi)

13.0
11.0
1728.0
1.0
3.14159265359
180.0


In [3]:
from math import ceil,floor,pow,log10,pi
print ceil(12.01)
print floor(11.999)
print pow(12,3)
print log10(10)
print radians(180)
print degrees(pi)

13.0
11.0
1728.0
1.0


NameError: name 'radians' is not defined

In [17]:
from math import *
print ceil(12.01)
print floor(11.999)
print pow(12,3)
print log10(10)
print radians(180)
print degrees(pi)

13.0
11.0
1728.0
1.0
3.14159265359
180.0


In [4]:
from math import *
print pi

3.14159265359


In [5]:
import numpy
print numpy.array([1,2,3,4])



[1 2 3 4]


In [8]:
import numpy
print dir(numpy)

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__config__', '__doc__', '__file__', '__git_revision__', '__name__', '__package__', '__path__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_

In [9]:
import numpy
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [10]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [11]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [12]:
from numpy import *
array([1,2,3])

array([1, 2, 3])

In [2]:
# user defined sample_mod module using 
import sample_mod
sample_mod.fun2()
sample_mod.fun1()
sample_mod.fun3()

fun2 :
fun1:
fun3


In [3]:
# user defined sample_mod module using 
import sample_mod as mod
mod.fun2()
mod.fun1()
mod.fun3()

fun2 :
fun1:
fun3


In [4]:
# user defined sample_mod module using 
from  sample_mod import fun2,fun1
fun2()
fun1()
fun3()
fun4()

fun2 :
fun1:


NameError: name 'fun3' is not defined

In [5]:
# user defined sample_mod module using 
from  sample_mod import *
fun2()
fun1()
fun3()
fun4()

fun2 :
fun1:
fun3
fun4


In [6]:
# user defined samle_pack package using 
import sample_pack

ImportError: No module named sample_pack

In [8]:
# user defined samle_pack package using 
import sample_pack
print dir(sample_pack)

['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'mod1', 'mod2', 'mod3']


In [9]:
# user defined samle_pack package using 
import sample_pack
print dir(sample_pack)

['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'mod1', 'mod2', 'mod3']


In [10]:
# user defined samle_pack package using 
import sample_pack
print dir(sample_pack)

['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'mod1', 'mod2', 'mod3']


In [11]:
import sample_pack
sample_pack.fun1()

AttributeError: 'module' object has no attribute 'fun1'