# create Pandas Series

In [1]:
import pandas as pd

In [2]:
a = pd.Series([1,2,3,4,5])

In [3]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(a)

pandas.core.series.Series

In [5]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
a[4]

5

In [9]:
a = pd.Series(['a','b','c'])

In [10]:
a

0    a
1    b
2    c
dtype: object

In [12]:
a = pd.date_range(start = '01-01-2019', end = '28-2-2019')

In [13]:
a

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
               '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
               '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
               '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
               '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01',
               '2019-02-02', '2019-02-03', '2019-02-04', '2019-02-05',
               '2019-02-06', '2019-02-07', '2019-02-08', '2019-02-09',
               '2019-02-10', '2019-02-11', '2019-02-12', '2019-02-13',
               '2019-02-14', '2019-02-15', '2019-02-16', '2019-02-17',
               '2019-02-18', '2019-02-19', '2019-02-20', '2019-02-21',
               '2019-02-22', '2019-02-23', '2019-02-24', '2019-02-25',
      

In [14]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# Pandas dataframe

In [16]:
import numpy as np

In [21]:
temp = np.random.randint(low = 20, high =100, size = [5,])
name = np.random.choice(['Abhay','Teclov','Geekshub','Ankit'],5)
random = np.random.choice([10,11,13,12,14],5)

In [22]:
random

array([12, 11, 14, 12, 13])

In [23]:
name

array(['Teclov', 'Geekshub', 'Geekshub', 'Abhay', 'Abhay'], dtype='<U8')

In [24]:
temp

array([35, 72, 50, 60, 32])

In [25]:
a = list(zip(temp, name, random))

In [26]:
a

[(35, 'Teclov', 12),
 (72, 'Geekshub', 11),
 (50, 'Geekshub', 14),
 (60, 'Abhay', 12),
 (32, 'Abhay', 13)]

In [27]:
df = pd.DataFrame(data = a, columns=['temp','name','random'])

In [28]:
df

temp      name  random
0    35    Teclov      12
1    72  Geekshub      11
2    50  Geekshub      14
3    60     Abhay      12
4    32     Abhay      13

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
temp = np.random.randint(low = 20, high =100, size = [5,])
name = np.random.choice(['Abhay','Teclov','Geekshub','Ankit'],5)
random = np.random.choice([10,11,13,12,14],5)

In [31]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})

In [32]:
type(df)

pandas.core.frame.DataFrame

In [33]:
df

temp      name  random
0    77    Teclov      12
1    86  Geekshub      13
2    42  Geekshub      10
3    40  Geekshub      11
4    98     Ankit      11

In [35]:
df.head(2)


temp      name  random
0    77    Teclov      12
1    86  Geekshub      13

In [37]:
df.tail(2)

temp      name  random
3    40  Geekshub      11
4    98     Ankit      11

In [38]:
df.shape

(5, 3)

In [39]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [40]:
df.name

0      Teclov
1    Geekshub
2    Geekshub
3    Geekshub
4       Ankit
Name: name, dtype: object

In [41]:
df['name']

0      Teclov
1    Geekshub
2    Geekshub
3    Geekshub
4       Ankit
Name: name, dtype: object

In [42]:
df.describe()

temp     random
count   5.000000   5.000000
mean   68.600000  11.400000
std    26.283074   1.140175
min    40.000000  10.000000
25%    42.000000  11.000000
50%    77.000000  11.000000
75%    86.000000  12.000000
max    98.000000  13.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
temp      5 non-null int32
name      5 non-null object
random    5 non-null int32
dtypes: int32(2), object(1)
memory usage: 160.0+ bytes


In [44]:
df.values


array([[77, 'Teclov', 12],
       [86, 'Geekshub', 13],
       [42, 'Geekshub', 10],
       [40, 'Geekshub', 11],
       [98, 'Ankit', 11]], dtype=object)

In [45]:
df

temp      name  random
0    77    Teclov      12
1    86  Geekshub      13
2    42  Geekshub      10
3    40  Geekshub      11
4    98     Ankit      11

In [50]:
df.set_index('name', inplace = True)

In [51]:
df

temp  random
name                  
Teclov      77      12
Geekshub    86      13
Geekshub    42      10
Geekshub    40      11
Ankit       98      11

In [52]:
df.sort_index(axis =0, ascending=True)

temp  random
name                  
Ankit       98      11
Geekshub    86      13
Geekshub    42      10
Geekshub    40      11
Teclov      77      12

In [57]:
df.sort_values(by ='random', ascending = True,inplace =True)

In [58]:
df

temp  random
name                  
Geekshub    42      10
Geekshub    40      11
Ankit       98      11
Teclov      77      12
Geekshub    86      13

In [60]:
df.drop(['random'], axis =1)

temp
name          
Geekshub    42
Geekshub    40
Ankit       98
Teclov      77
Geekshub    86

In [61]:
df.head()

temp  random
name                  
Geekshub    42      10
Geekshub    40      11
Ankit       98      11
Teclov      77      12
Geekshub    86      13

In [65]:
df.iloc[[1,2]]

temp  random
name                  
Geekshub    40      11
Ankit       98      11

In [63]:
df.iloc[1:3,1]

name
Geekshub    11
Ankit       11
Name: random, dtype: int32

In [66]:
df.iloc[[True,True,False,True]]

temp  random
name                  
Geekshub    42      10
Geekshub    40      11
Teclov      77      12

In [71]:
df.set_index('random',inplace=True)

KeyError: 'random'

In [72]:
df

temp
random      
10        42
11        40
11        98
12        77
13        86

In [79]:
df.loc[11]


temp
random      
11        40
11        98

In [83]:
df.loc[11,'temp']

random
11    40
11    98
Name: temp, dtype: int32

In [75]:
df.loc[[11,12,13]]

temp
random      
11        40
11        98
12        77
13        86

In [84]:
df.loc[12:'temp']

temp
random      
12        77
13        86

In [86]:
df.loc[[True, True, False, True]]

temp
random      
10        42
11        40
12        77

In [88]:
df.loc[df.temp > 90]

temp
random      
11        98

In [58]:
df.loc[(df.random > 13) | (df.random == 10),:]

name  random
temp                  
84       Ankit      10
43       Abhay      10
44      Teclov      10
92       Ankit      14
82      Teclov      10
70    Geekshub      10

In [8]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# Merging & concat
d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [3]:
d1

col1  number
0    a       1
1    b       2

In [4]:
d2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [9]:
pd.concat([d1,d2],axis =0)

animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4

In [10]:
pd.concat([d1,d2], axis =0, ignore_index=True)

animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
2   lion  NaN      c       3
3  tiger  NaN      d       4

In [11]:
pd.concat([d1,d2], axis = 1)

col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [12]:
d1 = pd.DataFrame({
    "city" : ["lucknow","kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [13]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [14]:
d2 = pd.DataFrame({
    "city" : ["delhi","lucknow","kanpur"],
    "humidity" : [68,65,75]
})

In [15]:
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [16]:
df = pd.merge(d1,d2, on='city')

In [18]:
df

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [19]:
pd.merge(d1,d2, on=['city'], how ='outer')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [21]:
pd.merge(d1, d2, on =['city'], how='left')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [73]:
# dataset from https://github.com/codebasics/py/blob/master/pandas/6_handling_missing_data_replace/weather_data.csv

In [22]:
df1 = pd.read_csv("weather_data.csv")

In [23]:
df1

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [24]:
# pip3 install openpyxl
df1.to_excel('df_xl.xlsx', sheet_name = 'weather_data')

In [25]:
# pip3 install xlrd
df2 = pd.read_excel('df_xl.xlsx')

In [27]:
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [29]:
df2.to_csv('file.csv')

In [30]:
df2.to_csv('file_noindex.csv', index = False)

In [31]:
df_group = df2.groupby("event")

In [32]:
df_group

In [84]:
for temperature in df_group:
    print(temperature)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)


In [33]:
df_group.get_group('Rain')

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [34]:
df_group.describe()

temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count   
event                                                                       
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0   
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0   
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0   

                                                 
      mean       std  min   25%  50%   75%  max  
event                                            
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0  
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [37]:
def hot_temp(x):
    return x > 30

In [38]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

In [39]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [40]:
df2['hot_temp'] = df2['temperature'].apply(lambda x: x > 30)

In [41]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [92]:
#pivot table

In [42]:
df2.pivot_table(values = 'temperature', index = 'event', aggfunc = 'mean')

temperature
event             
Rain            32
Snow            26
Sunny           33

In [43]:
df2.pivot_table(columns = 'temperature')

temperature     24     28    31    32    35
hot_temp     False  False  True  True  True
windspeed        7      2     2     5     7

In [96]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
    Create a spreadsheet-style pivot table as a DataFrame. The levels in
    the pivot table will be stored in MultiIndex objects (hierarchical
    indexes) on the index and columns of the result DataFrame
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types