# What is Data Preprocessing ?


  Data preprocessing is a data mining technique that involves transforming raw data into an        understandable format.

  Real-world data is often incomplete, inconsistent, and/or lacking in certain behaviors or        trends, and is likely to contain many errors.

  Data preprocessing is a proven method of resolving such issues.


# Steps in Data Preprocessing


	Step 1 : Import the libraries

	Step 2 : Import the data-set

	Step 3 : Check out the missing values

	Step 4 : See the Categorical Values
    
	Step 5 : Findout independed and depended variable

	Step 6 : Splitting the data-set into Training and Test Set

	Step 7 : Feature Scaling


# STEP 1 :  IMPORT THE LIBRARIES

In [ ]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


# STEP 2 : IMPORTING DATA SET


In [2]:
# step 2  importing the data set 
dataset= pd.read_csv('WorldCupMatches.csv')


In [3]:
dataset

Year              Datetime              Stage  \
0     1930.0  13 Jul 1930 - 15:00             Group 1   
1     1930.0  13 Jul 1930 - 15:00             Group 4   
2     1930.0  14 Jul 1930 - 12:45             Group 2   
3     1930.0  14 Jul 1930 - 14:50             Group 3   
4     1930.0  15 Jul 1930 - 16:00             Group 1   
5     1930.0  16 Jul 1930 - 14:45             Group 1   
6     1930.0  17 Jul 1930 - 12:45             Group 2   
7     1930.0  17 Jul 1930 - 14:45             Group 4   
8     1930.0  18 Jul 1930 - 14:30             Group 3   
9     1930.0  19 Jul 1930 - 12:50             Group 1   
10    1930.0  19 Jul 1930 - 15:00             Group 1   
11    1930.0  20 Jul 1930 - 13:00             Group 2   
12    1930.0  20 Jul 1930 - 15:00             Group 4   
13    1930.0  21 Jul 1930 - 14:50             Group 3   
14    1930.0  22 Jul 1930 - 14:45             Group 1   
15    1930.0  26 Jul 1930 - 14:45         Semi-finals   
16    1930.0  27 Jul 1930 - 14:45         Semi-finals   
17    1930.0  30 Jul 1930 - 14:15               Final   
18    1934.0  27 May 1934 - 16:30   Preliminary round   
19    1934.0  27 May 1934 - 16:30   Preliminary round   
20    1934.0  27 May 1934 - 16:30   Preliminary round   
21    1934.0  27 May 1934 - 16:30   Preliminary round   
22    1934.0  27 May 1934 - 16:30   Preliminary round   
23    1934.0  27 May 1934 - 16:30   Preliminary round   
24    1934.0  27 May 1934 - 16:30   Preliminary round   
25    1934.0  27 May 1934 - 16:30   Preliminary round   
26    1934.0  31 May 1934 - 16:30      Quarter-finals   
27    1934.0  31 May 1934 - 16:30      Quarter-finals   
28    1934.0  31 May 1934 - 16:30      Quarter-finals   
29    1934.0  31 May 1934 - 16:30      Quarter-finals   
...      ...                   ...                ...   
4542     NaN                   NaN                NaN   
4543     NaN                   NaN                NaN   
4544     NaN                   NaN                NaN   
4545     NaN                   NaN                NaN   
4546     NaN                   NaN                NaN   
4547     NaN                   NaN                NaN   
4548     NaN                   NaN                NaN   
4549     NaN                   NaN                NaN   
4550     NaN                   NaN                NaN   
4551     NaN                   NaN                NaN   
4552     NaN                   NaN                NaN   
4553     NaN                   NaN                NaN   
4554     NaN                   NaN                NaN   
4555     NaN                   NaN                NaN   
4556     NaN                   NaN                NaN   
4557     NaN                   NaN                NaN   
4558     NaN                   NaN                NaN   
4559     NaN                   NaN                NaN   
4560     NaN                   NaN                NaN   
4561     NaN                   NaN                NaN   
4562     NaN                   NaN                NaN   
4563     NaN                   NaN                NaN   
4564     NaN                   NaN                NaN   
4565     NaN                   NaN                NaN   
4566     NaN                   NaN                NaN   
4567     NaN                   NaN                NaN   
4568     NaN                   NaN                NaN   
4569     NaN                   NaN                NaN   
4570     NaN                   NaN                NaN   
4571     NaN                   NaN                NaN   

                      Stadium         City  Home Team Name  Home Team Goals  \
0                     Pocitos  Montevideo           France              4.0   
1              Parque Central  Montevideo              USA              3.0   
2              Parque Central  Montevideo       Yugoslavia              2.0   
3                     Pocitos  Montevideo          Romania              3.0   
4              Parque Central  Montevideo        Argentina              1.0   

In [4]:
dataset.shape


(4572, 20)

In [5]:
dataset.head()

Year              Datetime    Stage         Stadium         City  \
0  1930.0  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo    
1  1930.0  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo    
2  1930.0  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo    
3  1930.0  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo    
4  1930.0  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo    

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France              4.0              1.0         Mexico   
1            USA              3.0              0.0        Belgium   
2     Yugoslavia              2.0              1.0         Brazil   
3        Romania              3.0              1.0           Peru   
4      Argentina              1.0              0.0         France   

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                   3.0                   0.0   
1                    18346.0                   2.0                   0.0   
2                    24059.0                   2.0                   0.0   
3                     2549.0                   1.0                   0.0   
4                    23409.0                   0.0                   0.0   

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)   
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)   
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)   
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)   
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)   

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)    201.0   1096.0                FRA   
1       WARNKEN Alberto (CHI)    201.0   1090.0                USA   
2         BALWAY Thomas (FRA)    201.0   1093.0                YUG   
3    MATEUCCI Francisco (URU)    201.0   1098.0                ROU   
4  RADULESCU Constantin (ROU)    201.0   1085.0                ARG   

  Away Team Initials  
0                MEX  
1                BEL  
2                BRA  
3                PER  
4                FRA

In [6]:
dataset.columns

Index([u'Year', u'Datetime', u'Stage', u'Stadium', u'City', u'Home Team Name',
       u'Home Team Goals', u'Away Team Goals', u'Away Team Name',
       u'Win conditions', u'Attendance', u'Half-time Home Goals',
       u'Half-time Away Goals', u'Referee', u'Assistant 1', u'Assistant 2',
       u'RoundID', u'MatchID', u'Home Team Initials', u'Away Team Initials'],
      dtype='object')

In [7]:
dataset.index


RangeIndex(start=0, stop=4572, step=1)

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
Year                    852 non-null float64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null float64
Away Team Goals         852 non-null float64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null float64
Half-time Away Goals    852 non-null float64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null float64
MatchID                 852 non-null float64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtype

# STEP 3 :  Check out the Missing Values

	The concept of missing values is important to understand in order to successfully manage         data. 

	If the missing values are not handled properly by the researcher, then he/she may end up          drawing an inaccurate inference about the data. 

	Due to improper handling, the result obtained by the researcher will differ from ones where       the missing values are present.


# Two ways to handle Missing Values

In [9]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [10]:
dataset.shape

(4572, 20)

#  Method1 :-

	This method commonly used to handle the null values.

	Here, we either delete a particular row if it has a null value for a particular feature and a      particular column if it has more than 75% of missing values.

	This method is advised only when there are enough samples in the data set. 



In [11]:
dataset.dropna(inplace=False)


Year              Datetime                     Stage  \
0    1930.0  13 Jul 1930 - 15:00                    Group 1   
1    1930.0  13 Jul 1930 - 15:00                    Group 4   
2    1930.0  14 Jul 1930 - 12:45                    Group 2   
3    1930.0  14 Jul 1930 - 14:50                    Group 3   
4    1930.0  15 Jul 1930 - 16:00                    Group 1   
5    1930.0  16 Jul 1930 - 14:45                    Group 1   
6    1930.0  17 Jul 1930 - 12:45                    Group 2   
7    1930.0  17 Jul 1930 - 14:45                    Group 4   
8    1930.0  18 Jul 1930 - 14:30                    Group 3   
9    1930.0  19 Jul 1930 - 12:50                    Group 1   
10   1930.0  19 Jul 1930 - 15:00                    Group 1   
11   1930.0  20 Jul 1930 - 13:00                    Group 2   
12   1930.0  20 Jul 1930 - 15:00                    Group 4   
13   1930.0  21 Jul 1930 - 14:50                    Group 3   
14   1930.0  22 Jul 1930 - 14:45                    Group 1   
15   1930.0  26 Jul 1930 - 14:45                Semi-finals   
16   1930.0  27 Jul 1930 - 14:45                Semi-finals   
17   1930.0  30 Jul 1930 - 14:15                      Final   
18   1934.0  27 May 1934 - 16:30          Preliminary round   
19   1934.0  27 May 1934 - 16:30          Preliminary round   
20   1934.0  27 May 1934 - 16:30          Preliminary round   
21   1934.0  27 May 1934 - 16:30          Preliminary round   
22   1934.0  27 May 1934 - 16:30          Preliminary round   
23   1934.0  27 May 1934 - 16:30          Preliminary round   
24   1934.0  27 May 1934 - 16:30          Preliminary round   
25   1934.0  27 May 1934 - 16:30          Preliminary round   
26   1934.0  31 May 1934 - 16:30             Quarter-finals   
27   1934.0  31 May 1934 - 16:30             Quarter-finals   
28   1934.0  31 May 1934 - 16:30             Quarter-finals   
29   1934.0  31 May 1934 - 16:30             Quarter-finals   
..      ...                   ...                       ...   
820  2014.0  28 Jun 2014 - 13:00                Round of 16   
821  2014.0  28 Jun 2014 - 17:00                Round of 16   
822  2014.0  30 Jun 2014 - 13:00                Round of 16   
824  2014.0  04 Jul 2014 - 17:00             Quarter-finals   
825  2014.0  04 Jul 2014 - 13:00             Quarter-finals   
826  2014.0  08 Jul 2014 - 17:00                Semi-finals   
827  2014.0  12 Jul 2014 - 17:00   Play-off for third place   
828  2014.0  13 Jul 2014 - 16:00                      Final   
829  2014.0  09 Jul 2014 - 17:00                Semi-finals   
830  2014.0  05 Jul 2014 - 17:00             Quarter-finals   
831  2014.0  05 Jul 2014 - 13:00             Quarter-finals   
832  2014.0  29 Jun 2014 - 13:00                Round of 16   
833  2014.0  29 Jun 2014 - 17:00                Round of 16   
834  2014.0  01 Jul 2014 - 13:00                Round of 16   
835  2014.0  01 Jul 2014 - 17:00                Round of 16   
836  2014.0  28 Jun 2014 - 13:00                Round of 16   
837  2014.0  28 Jun 2014 - 17:00                Round of 16   
838  2014.0  29 Jun 2014 - 13:00                Round of 16   
839  2014.0  29 Jun 2014 - 17:00                Round of 16   
840  2014.0  30 Jun 2014 - 13:00                Round of 16   
842  2014.0  01 Jul 2014 - 13:00                Round of 16   
843  2014.0  01 Jul 2014 - 17:00                Round of 16   
844  2014.0  04 Jul 2014 - 13:00             Quarter-finals   
845  2014.0  04 Jul 2014 - 17:00             Quarter-finals   
846  2014.0  05 Jul 2014 - 13:00             Quarter-finals   
847  2014.0  05 Jul 2014 - 17:00             Quarter-finals   
848  2014.0  08 Jul 2014 - 17:00                Semi-finals   
849  2014.0  09 Jul 2014 - 17:00                Semi-finals   
850  2014.0  12 Jul 2014 - 17:00   Play-off for third place   
851  2014.0  13 Jul 2014 - 16:00                      Final   

                     Stadium             City  Home Team Name  \
0                    Pocitos      M

In [12]:
dataset.isnull().sum()


Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [13]:
dataset.shape

(4572, 20)

In [14]:
dataset.dropna(inplace=True)
dataset.isnull().sum()


Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

# Method2:-

	This strategy can be applied on a feature which has numeric data like the year column or Home team goal column. 

	We can calculate the mean, median or mode of the feature and replace it with the missing values. 

	This is an approximation which can add variance to the data set. 

	But the loss of the data can be negated by this method which yields better results compared to removal of rows and columns. 

	Replacing with the above three approximations are a statistical approach of handling the missing values. 

	This method is also called as leaking the data while training. 

	Another way is to approximate it with the deviation of neighbouring values. This works better if the data is linear.


In [15]:
dataset =pd.read_csv("WorldCupMatches.csv")

In [16]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [17]:
# replace the NaN value with mean ,median or mode methode 2
dataset['Year'].mean()

1985.0892018779343

In [18]:
dataset['Year'].tail()

4567   NaN
4568   NaN
4569   NaN
4570   NaN
4571   NaN
Name: Year, dtype: float64

In [19]:
dataset['Year'].replace(np.NaN,dataset['Year'].mean()).tail()

4567    1985.089202
4568    1985.089202
4569    1985.089202
4570    1985.089202
4571    1985.089202
Name: Year, dtype: float64

In [ ]:
# do the above operation for all columns 

# See the Categorical Values

	Machine learning models are based on Mathematical equations and you can intuitively understand that it would cause some problem if we can keep the Categorical data in the equations because we would only want numbers in the equations.


In [20]:
import pandas as pd

In [21]:
# importing Data csv file
dataset = pd.read_csv('Data.csv')


In [22]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [23]:
dataset.Purchased.replace(('Yes', 'No'), (1, 0), inplace=True)


In [24]:
dataset

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [25]:
dataset.tail()

Country   Age   Salary  Purchased
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [26]:
X = dataset.iloc[:, :-1].values  # feature varibale / independed variable
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [27]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [28]:
dataset.dropna(inplace=True)

In [29]:
dataset.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [30]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Working on Categorical Values 

	So, we need to encode the Categorical Variable…..

	To convert Categorical variable into Numerical data we can use LabelEncoder() class from preprocessing library.

In [31]:
# working on categorical Data
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


In [32]:
X =dataset.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [33]:
X[: ,0]

array(['France', 'Spain', 'Germany', 'Spain', 'France', 'France',
       'Germany', 'France'], dtype=object)

In [34]:
X[:,0] =label_encoder.fit_transform(X[:,0])
X[:,0]

array([0, 2, 1, 2, 0, 0, 1, 0], dtype=object)

In [35]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [0, 35.0, 58000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [36]:
import numpy as np

In [37]:
X=np.array(X,dtype='int32')
X

array([[    0,    44, 72000],
       [    2,    27, 48000],
       [    1,    30, 54000],
       [    2,    38, 61000],
       [    0,    35, 58000],
       [    0,    48, 79000],
       [    1,    50, 83000],
       [    0,    37, 67000]])

In [38]:
X.ndim

2

In [39]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])


In [40]:
X

array([[    0,    44, 72000],
       [    2,    27, 48000],
       [    1,    30, 54000],
       [    2,    38, 61000],
       [    0,    35, 58000],
       [    0,    48, 79000],
       [    1,    50, 83000],
       [    0,    37, 67000]])

In [41]:
x = onehotencoder.fit_transform(X)
print(x)

C:\Users\ADMIN\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


  (0, 0)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 1)	1.0
  (7, 0)	1.0
  (0, 3)	44.0
  (0, 4)	72000.0
  (1, 3)	27.0
  (1, 4)	48000.0
  (2, 3)	30.0
  (2, 4)	54000.0
  (3, 3)	38.0
  (3, 4)	61000.0
  (4, 3)	35.0
  (4, 4)	58000.0
  (5, 3)	48.0
  (5, 4)	79000.0
  (6, 3)	50.0
  (6, 4)	83000.0
  (7, 3)	37.0
  (7, 4)	67000.0



	But there is a problem in it, the problem is still the same, machine learning models are based on equations and that’s good that we replaced the text by numbers so that we can include the numbers in the equations.

	However, since 1>0 and 2>1(See the above data-set) , the equations in the model will think that Spain has a higher value than Germany and France, and Germany has a higher value than France.

	Actually, this is a not the case, these are actually three Categories and there is no relational order between the three. So , we have to prevent this, we’re going to use what are Dummy Variables.


# What is Dummy Variables ?


  Dummy Variables is one that takes the value 0 or 1 to indicate the absence or presence of some categorical effect that may be expected to shift the outcome.


          Number of Columns = Number of Categories



# Working on Dummy Variable 


   To create dummy variable we are going to use OneHotEncoder Class from sklearn.preprocessing or you can use pandas get dummies method.


   I will show you with pandas how to use get_dummies( ) for creating Dummy Variables.

In [43]:
dummy =pd.get_dummies(dataset['Country'])
dummy


France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
5       1        0      0
7       1        0      0
8       0        1      0
9       1        0      0

In [44]:

dataset = pd.concat([dataset,dummy],axis=1)
dataset

Country   Age   Salary  Purchased  France  Germany  Spain
0   France  44.0  72000.0          0       1        0      0
1    Spain  27.0  48000.0          1       0        0      1
2  Germany  30.0  54000.0          0       0        1      0
3    Spain  38.0  61000.0          0       0        0      1
5   France  35.0  58000.0          1       1        0      0
7   France  48.0  79000.0          1       1        0      0
8  Germany  50.0  83000.0          0       0        1      0
9   France  37.0  67000.0          1       1        0      0

In [63]:
dataset

Country   Age   Salary  Purchased  France  Germany  Spain
0   France  44.0  72000.0          0       1        0      0
1    Spain  27.0  48000.0          1       0        0      1
2  Germany  30.0  54000.0          0       0        1      0
3    Spain  38.0  61000.0          0       0        0      1
5   France  35.0  58000.0          1       1        0      0
7   France  48.0  79000.0          1       1        0      0
8  Germany  50.0  83000.0          0       0        1      0
9   France  37.0  67000.0          1       1        0      0

In [45]:

dataset = dataset.drop(['Country'],axis=1)


In [46]:
dataset

Age   Salary  Purchased  France  Germany  Spain
0  44.0  72000.0          0       1        0      0
1  27.0  48000.0          1       0        0      1
2  30.0  54000.0          0       0        1      0
3  38.0  61000.0          0       0        0      1
5  35.0  58000.0          1       1        0      0
7  48.0  79000.0          1       1        0      0
8  50.0  83000.0          0       0        1      0
9  37.0  67000.0          1       1        0      0

In [47]:
dataset.dropna(inplace=True)


In [48]:
dataset

Age   Salary  Purchased  France  Germany  Spain
0  44.0  72000.0          0       1        0      0
1  27.0  48000.0          1       0        0      1
2  30.0  54000.0          0       0        1      0
3  38.0  61000.0          0       0        0      1
5  35.0  58000.0          1       1        0      0
7  48.0  79000.0          1       1        0      0
8  50.0  83000.0          0       0        1      0
9  37.0  67000.0          1       1        0      0

In [49]:
y=dataset.iloc[:,2].values
y

array([0, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [51]:
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split


In [52]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)
X_train

array([[    2,    27, 48000],
       [    0,    35, 58000],
       [    0,    44, 72000],
       [    2,    38, 61000],
       [    0,    48, 79000],
       [    0,    37, 67000]])

In [53]:
X_test

array([[    1,    50, 83000],
       [    1,    30, 54000]])

In [54]:
y_train

array([1, 1, 0, 0, 1, 1], dtype=int64)

In [55]:
y_test

array([0, 0], dtype=int64)

In [56]:
X

array([[    0,    44, 72000],
       [    2,    27, 48000],
       [    1,    30, 54000],
       [    2,    38, 61000],
       [    0,    35, 58000],
       [    0,    48, 79000],
       [    1,    50, 83000],
       [    0,    37, 67000]])

#                                Feature Scaling


# What is Feature Scaling ?

	Feature scaling is the method to limit the range of variables so that they can be compared on common grounds.

	Suppose we have this data-set

	See the Age and Salary column. You can easily noticed Salary and Age variable don’t have the same scale and this will cause some issue in your machine learning model.

	Because most of the Machine Learning models are based on Euclidean Distance.
 
	Let’s say we take two values from Age and Salary column

	One can easily compute and see that Salary column will be dominated in Euclidean Distance. And we don’t want this thing.



# Feature Scaling or Standardization:


	It is a step of Data Pre Processing which is applied to independent variables or features of data. 

	It basically helps to normalise the data within a particular range. 

	Sometimes, it also helps in speeding up the calculations in an algorithm.

from sklearn.preprocessing import StandardScaler

	Formula	used	in	Backend	Standardisation replaces the values	by	their	Z	scores.
 
	Mostly the Fit method is used for Feature scaling
fit(X, y = None)


In [1]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler 
# Read Data from CSV 
data = pd.read_csv('Data.csv') 
print(data.head() )
print('----------------')
print(data.isnull().sum())
print('----------------')
data.dropna(inplace =True)
print(data.head())
print('-------------------')
print(data.isnull().sum())
print('-------------------')
data.Purchased.replace(('No','Yes'),(0,1),inplace =True)
print(data.head() )
print('----------------')
dummy =pd.get_dummies(data['Country'])
print(dummy)
data = pd.concat([data,dummy],axis=1)
print('------------------')
print(data.head() )
print('----------------')
data.drop(columns='Country',inplace =True)
print(data.head() )
print('----------------')

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
----------------
Country      0
Age          1
Salary       1
Purchased    0
dtype: int64
----------------
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
-------------------
Country      0
Age          0
Salary       0
Purchased    0
dtype: int64
-------------------
   Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
----------------
   France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3    

In [2]:
import warnings 
warnings.filterwarnings('ignore')
# Initialise the Scaler 
print("---------------------")
scaler = StandardScaler() 
# To scale data 
data1=scaler.fit_transform(data) 
print(data1)

---------------------
[[ 0.69985807  0.58989097 -1.          1.         -0.57735027 -0.57735027]
 [-1.51364653 -1.50749915  1.         -1.         -0.57735027  1.73205081]
 [-1.12302807 -0.98315162 -1.         -1.          1.73205081 -0.57735027]
 [-0.08137885 -0.37141284 -1.         -1.         -0.57735027  1.73205081]
 [-0.47199731 -0.6335866   1.          1.         -0.57735027 -0.57735027]
 [ 1.22068269  1.20162976  1.          1.         -0.57735027 -0.57735027]
 [ 1.48109499  1.55119478 -1.         -1.          1.73205081 -0.57735027]
 [-0.211585    0.1529347   1.          1.         -0.57735027 -0.57735027]]


In [3]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler =MinMaxScaler()
data2 =min_max_scaler.fit_transform(data)
print(data2)

[[0.73913043 0.68571429 0.         1.         0.         0.        ]
 [0.         0.         1.         0.         0.         1.        ]
 [0.13043478 0.17142857 0.         0.         1.         0.        ]
 [0.47826087 0.37142857 0.         0.         0.         1.        ]
 [0.34782609 0.28571429 1.         1.         0.         0.        ]
 [0.91304348 0.88571429 1.         1.         0.         0.        ]
 [1.         1.         0.         0.         1.         0.        ]
 [0.43478261 0.54285714 1.         1.         0.         0.        ]]
