# What is Data Preprocessing ?


  Data preprocessing is a data mining technique that involves transforming raw data into an        understandable format.

  Real-world data is often incomplete, inconsistent, and/or lacking in certain behaviors or        trends, and is likely to contain many errors.

  Data preprocessing is a proven method of resolving such issues.


# Steps in Data Preprocessing


	Step 1 : Import the libraries

	Step 2 : Import the data-set

	Step 3 : Check out the missing values

	Step 4 : See the Categorical Values

	Step 5 : Find out depended and independed values

	Step 6 : Feature Scaling


# STEP 1 :  IMPORT THE LIBRARIES

In [1]:
# step 1 importing modules 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')

# STEP 2 : IMPORTING DATA SET


In [2]:
# step 2  importing the data set 
dataset= pd.read_csv('WorldCupMatches.csv')


In [3]:
dataset

Year              Datetime              Stage  \
0     1930.0  13 Jul 1930 - 15:00             Group 1   
1     1930.0  13 Jul 1930 - 15:00             Group 4   
2     1930.0  14 Jul 1930 - 12:45             Group 2   
3     1930.0  14 Jul 1930 - 14:50             Group 3   
4     1930.0  15 Jul 1930 - 16:00             Group 1   
5     1930.0  16 Jul 1930 - 14:45             Group 1   
6     1930.0  17 Jul 1930 - 12:45             Group 2   
7     1930.0  17 Jul 1930 - 14:45             Group 4   
8     1930.0  18 Jul 1930 - 14:30             Group 3   
9     1930.0  19 Jul 1930 - 12:50             Group 1   
10    1930.0  19 Jul 1930 - 15:00             Group 1   
11    1930.0  20 Jul 1930 - 13:00             Group 2   
12    1930.0  20 Jul 1930 - 15:00             Group 4   
13    1930.0  21 Jul 1930 - 14:50             Group 3   
14    1930.0  22 Jul 1930 - 14:45             Group 1   
15    1930.0  26 Jul 1930 - 14:45         Semi-finals   
16    1930.0  27 Jul 1930 - 14:45         Semi-finals   
17    1930.0  30 Jul 1930 - 14:15               Final   
18    1934.0  27 May 1934 - 16:30   Preliminary round   
19    1934.0  27 May 1934 - 16:30   Preliminary round   
20    1934.0  27 May 1934 - 16:30   Preliminary round   
21    1934.0  27 May 1934 - 16:30   Preliminary round   
22    1934.0  27 May 1934 - 16:30   Preliminary round   
23    1934.0  27 May 1934 - 16:30   Preliminary round   
24    1934.0  27 May 1934 - 16:30   Preliminary round   
25    1934.0  27 May 1934 - 16:30   Preliminary round   
26    1934.0  31 May 1934 - 16:30      Quarter-finals   
27    1934.0  31 May 1934 - 16:30      Quarter-finals   
28    1934.0  31 May 1934 - 16:30      Quarter-finals   
29    1934.0  31 May 1934 - 16:30      Quarter-finals   
...      ...                   ...                ...   
4542     NaN                   NaN                NaN   
4543     NaN                   NaN                NaN   
4544     NaN                   NaN                NaN   
4545     NaN                   NaN                NaN   
4546     NaN                   NaN                NaN   
4547     NaN                   NaN                NaN   
4548     NaN                   NaN                NaN   
4549     NaN                   NaN                NaN   
4550     NaN                   NaN                NaN   
4551     NaN                   NaN                NaN   
4552     NaN                   NaN                NaN   
4553     NaN                   NaN                NaN   
4554     NaN                   NaN                NaN   
4555     NaN                   NaN                NaN   
4556     NaN                   NaN                NaN   
4557     NaN                   NaN                NaN   
4558     NaN                   NaN                NaN   
4559     NaN                   NaN                NaN   
4560     NaN                   NaN                NaN   
4561     NaN                   NaN                NaN   
4562     NaN                   NaN                NaN   
4563     NaN                   NaN                NaN   
4564     NaN                   NaN                NaN   
4565     NaN                   NaN                NaN   
4566     NaN                   NaN                NaN   
4567     NaN                   NaN                NaN   
4568     NaN                   NaN                NaN   
4569     NaN                   NaN                NaN   
4570     NaN                   NaN                NaN   
4571     NaN                   NaN                NaN   

                      Stadium         City  Home Team Name  Home Team Goals  \
0                     Pocitos  Montevideo           France              4.0   
1              Parque Central  Montevideo              USA              3.0   
2              Parque Central  Montevideo       Yugoslavia              2.0   
3                     Pocitos  Montevideo          Romania              3.0   
4              Parque Central  Montevideo        Argentina              1.0   

In [3]:
dataset.shape


(4572, 20)

In [5]:
dataset.head() # show the 1st 5 records 

Year              Datetime    Stage         Stadium         City  \
0  1930.0  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo    
1  1930.0  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo    
2  1930.0  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo    
3  1930.0  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo    
4  1930.0  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo    

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France              4.0              1.0         Mexico   
1            USA              3.0              0.0        Belgium   
2     Yugoslavia              2.0              1.0         Brazil   
3        Romania              3.0              1.0           Peru   
4      Argentina              1.0              0.0         France   

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                   3.0                   0.0   
1                    18346.0                   2.0                   0.0   
2                    24059.0                   2.0                   0.0   
3                     2549.0                   1.0                   0.0   
4                    23409.0                   0.0                   0.0   

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)   
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)   
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)   
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)   
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)   

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)    201.0   1096.0                FRA   
1       WARNKEN Alberto (CHI)    201.0   1090.0                USA   
2         BALWAY Thomas (FRA)    201.0   1093.0                YUG   
3    MATEUCCI Francisco (URU)    201.0   1098.0                ROU   
4  RADULESCU Constantin (ROU)    201.0   1085.0                ARG   

  Away Team Initials  
0                MEX  
1                BEL  
2                BRA  
3                PER  
4                FRA

In [6]:
dataset.tail() # show the last 5 records 

Year Datetime Stage Stadium City Home Team Name  Home Team Goals  \
4567   NaN      NaN   NaN     NaN  NaN            NaN              NaN   
4568   NaN      NaN   NaN     NaN  NaN            NaN              NaN   
4569   NaN      NaN   NaN     NaN  NaN            NaN              NaN   
4570   NaN      NaN   NaN     NaN  NaN            NaN              NaN   
4571   NaN      NaN   NaN     NaN  NaN            NaN              NaN   

      Away Team Goals Away Team Name Win conditions  Attendance  \
4567              NaN            NaN            NaN         NaN   
4568              NaN            NaN            NaN         NaN   
4569              NaN            NaN            NaN         NaN   
4570              NaN            NaN            NaN         NaN   
4571              NaN            NaN            NaN         NaN   

      Half-time Home Goals  Half-time Away Goals Referee Assistant 1  \
4567                   NaN                   NaN     NaN         NaN   
4568                   NaN                   NaN     NaN         NaN   
4569                   NaN                   NaN     NaN         NaN   
4570                   NaN                   NaN     NaN         NaN   
4571                   NaN                   NaN     NaN         NaN   

     Assistant 2  RoundID  MatchID Home Team Initials Away Team Initials  
4567         NaN      NaN      NaN                NaN                NaN  
4568         NaN      NaN      NaN                NaN                NaN  
4569         NaN      NaN      NaN                NaN                NaN  
4570         NaN      NaN      NaN                NaN                NaN  
4571         NaN      NaN      NaN                NaN                NaN

In [7]:
len(dataset.columns)# find the no of features / columns 

20

In [7]:
dataset.index # find the  no of records 


RangeIndex(start=0, stop=4572, step=1)

In [8]:
dataset.info

<bound method DataFrame.info of         Year              Datetime              Stage  \
0     1930.0  13 Jul 1930 - 15:00             Group 1   
1     1930.0  13 Jul 1930 - 15:00             Group 4   
2     1930.0  14 Jul 1930 - 12:45             Group 2   
3     1930.0  14 Jul 1930 - 14:50             Group 3   
4     1930.0  15 Jul 1930 - 16:00             Group 1   
5     1930.0  16 Jul 1930 - 14:45             Group 1   
6     1930.0  17 Jul 1930 - 12:45             Group 2   
7     1930.0  17 Jul 1930 - 14:45             Group 4   
8     1930.0  18 Jul 1930 - 14:30             Group 3   
9     1930.0  19 Jul 1930 - 12:50             Group 1   
10    1930.0  19 Jul 1930 - 15:00             Group 1   
11    1930.0  20 Jul 1930 - 13:00             Group 2   
12    1930.0  20 Jul 1930 - 15:00             Group 4   
13    1930.0  21 Jul 1930 - 14:50             Group 3   
14    1930.0  22 Jul 1930 - 14:45             Group 1   
15    1930.0  26 Jul 1930 - 14:45         Semi-finals   

In [4]:
dataset.describe()

Year  Home Team Goals  Away Team Goals     Attendance  \
count   852.000000       852.000000       852.000000     850.000000   
mean   1985.089202         1.811033         1.022300   45164.800000   
std      22.448825         1.610255         1.087573   23485.249247   
min    1930.000000         0.000000         0.000000    2000.000000   
25%    1970.000000         1.000000         0.000000   30000.000000   
50%    1990.000000         2.000000         1.000000   41579.500000   
75%    2002.000000         3.000000         2.000000   61374.500000   
max    2014.000000        10.000000         7.000000  173850.000000   

       Half-time Home Goals  Half-time Away Goals       RoundID       MatchID  
count            852.000000            852.000000  8.520000e+02  8.520000e+02  
mean               0.708920              0.428404  1.066177e+07  6.134687e+07  
std                0.937414              0.691252  2.729613e+07  1.110572e+08  
min                0.000000              0.000000  2.010000e+02  2.500000e+01  
25%                0.000000              0.000000  2.620000e+02  1.188750e+03  
50%                0.000000              0.000000  3.370000e+02  2.191000e+03  
75%                1.000000              1.000000  2.497220e+05  4.395006e+07  
max                6.000000              5.000000  9.741060e+07  3.001865e+08

# STEP 3 :  Check out the Missing Values

	The concept of missing values is important to understand in order to successfully manage         data. 

	If the missing values are not handled properly by the researcher, then he/she may end up          drawing an inaccurate inference about the data. 

	Due to improper handling, the result obtained by the researcher will differ from ones where       the missing values are present.


# Two ways to handle Missing Values

In [5]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [6]:
dataset.shape

(4572, 20)

In [7]:
3720 / 4572 *100

81.36482939632546

#  Method1 :-

	This method commonly used to handle the null values.

	Here, we either delete a particular row if it has a null value for a particular feature and a      particular column if it has more than 75% of missing values.

	This method is advised only when there are enough samples in the data set. 



In [15]:
data =dataset.dropna(inplace=False)


In [16]:
dataset.shape

(4572, 20)

In [17]:
data.shape

(850, 20)

In [18]:
data.isnull().sum()


Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [16]:
data.shape

(850, 20)

# Method2:-

	This strategy can be applied on a feature which has numeric data like the year column or Home team goal column. 

	We can calculate the mean, median or mode of the feature and replace it with the missing values. 

	This is an approximation which can add variance to the data set. 

	But the loss of the data can be negated by this method which yields better results compared to removal of rows and columns. 

	Replacing with the above three approximations are a statistical approach of handling the missing values. 

	This method is also called as leaking the data while training. 

	Another way is to approximate it with the deviation of neighbouring values. This works better if the data is linear.


In [8]:
# replace the NaN value with mean ,median or mode methode 2
int(dataset['Year'].mean())

1985

In [9]:
dataset.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [10]:
dataset['Year'].tail()

4567   NaN
4568   NaN
4569   NaN
4570   NaN
4571   NaN
Name: Year, dtype: float64

In [9]:
dataset['Year'].replace(np.NaN,int(dataset['Year'].mean()),inplace=True)

In [10]:
dataset['Year'].tail()

4567    1985.0
4568    1985.0
4569    1985.0
4570    1985.0
4571    1985.0
Name: Year, dtype: float64

# See the Categorical Values

	Machine learning models are based on Mathematical equations and you can intuitively understand that it would cause some problem if we can keep the Categorical data in the equations because we would only want numbers in the equations.


In [1]:
import numpy as np
import pandas as pd


In [2]:
# importing Data csv file
dataset = pd.read_csv('Data.csv')


In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 392.0+ bytes


In [5]:
dataset.Purchased.replace(('Yes', 'No'), (1, 0), inplace=True)


In [6]:
dataset

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [9]:
dataset.tail()

Country   Age   Salary  Purchased
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [11]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [12]:
data = dataset.dropna(inplace=False)

In [14]:
data

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [15]:
dataset

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [16]:
dataset.Age.replace(np.NaN,data.Age.mean(),inplace=True)

In [17]:
dataset.Salary.replace(np.NaN,data.Salary.mean(),inplace=True)

In [19]:
dataset

Country     Age   Salary  Purchased
0   France  44.000  72000.0          0
1    Spain  27.000  48000.0          1
2  Germany  30.000  54000.0          0
3    Spain  38.000  61000.0          0
4  Germany  40.000  65250.0          1
5   France  35.000  58000.0          1
6    Spain  38.625  52000.0          0
7   France  48.000  79000.0          1
8  Germany  50.000  83000.0          0
9   France  37.000  67000.0          1

In [20]:
dataset.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [29]:
dataset

Country     Age   Salary  Purchased
0   France  44.000  72000.0          0
1    Spain  27.000  48000.0          1
2  Germany  30.000  54000.0          0
3    Spain  38.000  61000.0          0
4  Germany  40.000  65250.0          1
5   France  35.000  58000.0          1
6    Spain  38.625  52000.0          0
7   France  48.000  79000.0          1
8  Germany  50.000  83000.0          0
9   France  37.000  67000.0          1

In [22]:
X = dataset.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 65250.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.625, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [24]:
X.shape

(10L, 3L)

In [25]:
X.ndim

2

# Working on Categorical Values 

	So, we need to encode the Categorical Variable…..

	To convert Categorical variable into Numerical data we can use LabelEncoder() class from preprocessing library.

In [26]:
X = dataset.iloc[:,0:-1]

In [27]:
X

Country     Age   Salary
0   France  44.000  72000.0
1    Spain  27.000  48000.0
2  Germany  30.000  54000.0
3    Spain  38.000  61000.0
4  Germany  40.000  65250.0
5   France  35.000  58000.0
6    Spain  38.625  52000.0
7   France  48.000  79000.0
8  Germany  50.000  83000.0
9   France  37.000  67000.0

In [29]:
y =dataset.iloc[:,-1]

In [30]:
y.ndim

1

In [31]:
# working on categorical Data
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [32]:
X = dataset.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 65250.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.625, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [33]:
X[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [34]:
X[:,0] =label_encoder.fit_transform(X[:,0])
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [36]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 65250.0],
       [0, 35.0, 58000.0],
       [2, 38.625, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [38]:
type(X)

numpy.ndarray

In [39]:
X.ndim

2

In [41]:
X=np.array(X,dtype='int32')
X

array([[    0,    44, 72000],
       [    2,    27, 48000],
       [    1,    30, 54000],
       [    2,    38, 61000],
       [    1,    40, 65250],
       [    0,    35, 58000],
       [    2,    38, 52000],
       [    0,    48, 79000],
       [    1,    50, 83000],
       [    0,    37, 67000]])

In [42]:
X.dtype

dtype('int32')


	But there is a problem in it, the problem is still the same, machine learning models are based on equations and that’s good that we replaced the text by numbers so that we can include the numbers in the equations.

	However, since 1>0 and 2>1(See the above data-set) , the equations in the model will think that Spain has a higher value than Germany and France, and Germany has a higher value than France.

	Actually, this is a not the case, these are actually three Categories and there is no relational order between the three. So , we have to prevent this, we’re going to use what are Dummy Variables.


# What is Dummy Variables ?


  Dummy Variables is one that takes the value 0 or 1 to indicate the absence or presence of some categorical effect that may be expected to shift the outcome.


          Number of Columns = Number of Categories



# Working on Dummy Variable 


   To create dummy variable we are going to use OneHotEncoder Class from sklearn.preprocessing or you can use pandas get dummies method.


   I will show you with pandas how to use get_dummies( ) for creating Dummy Variables.

In [44]:
dummy =pd.get_dummies(dataset['Country'])
dummy


France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [45]:

dataset =pd.concat([dataset,dummy],axis=1)
dataset

Country     Age   Salary  Purchased  France  Germany  Spain
0   France  44.000  72000.0          0       1        0      0
1    Spain  27.000  48000.0          1       0        0      1
2  Germany  30.000  54000.0          0       0        1      0
3    Spain  38.000  61000.0          0       0        0      1
4  Germany  40.000  65250.0          1       0        1      0
5   France  35.000  58000.0          1       1        0      0
6    Spain  38.625  52000.0          0       0        0      1
7   France  48.000  79000.0          1       1        0      0
8  Germany  50.000  83000.0          0       0        1      0
9   France  37.000  67000.0          1       1        0      0

In [46]:

dataset = dataset.drop(columns='Country')


In [47]:
dataset

Age   Salary  Purchased  France  Germany  Spain
0  44.000  72000.0          0       1        0      0
1  27.000  48000.0          1       0        0      1
2  30.000  54000.0          0       0        1      0
3  38.000  61000.0          0       0        0      1
4  40.000  65250.0          1       0        1      0
5  35.000  58000.0          1       1        0      0
6  38.625  52000.0          0       0        0      1
7  48.000  79000.0          1       1        0      0
8  50.000  83000.0          0       0        1      0
9  37.000  67000.0          1       1        0      0

In [48]:

y=dataset.iloc[:,2].values
y.shape

(10L,)

In [49]:
X.shape

(10L, 3L)

In [56]:
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)
X_train

array([[2, 38.625, 52000.0],
       [1, 40.0, 65250.0],
       [0, 37.0, 67000.0],
       [0, 48.0, 79000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [57]:
X_test

array([[2, 27.0, 48000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [58]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [59]:
y_test

array([1, 1], dtype=int64)

In [60]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 65250.0],
       [0, 35.0, 58000.0],
       [2, 38.625, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

#                                Feature Scaling


# What is Feature Scaling ?

	Feature scaling is the method to limit the range of variables so that they can be compared on common grounds.

	Suppose we have this data-set

	See the Age and Salary column. You can easily noticed Salary and Age variable don’t have the same scale and this will cause some issue in your machine learning model.

	Because most of the Machine Learning models are based on Euclidean Distance.
 
	Let’s say we take two values from Age and Salary column

	One can easily compute and see that Salary column will be dominated in Euclidean Distance. And we don’t want this thing.



# Feature Scaling or Standardization:


	It is a step of Data Pre Processing which is applied to independent variables or features of data. 

	It basically helps to normalise the data within a particular range. 

	Sometimes, it also helps in speeding up the calculations in an algorithm.

from sklearn.preprocessing import StandardScaler

	Formula	used	in	Backend	Standardisation replaces the values	by	their	Z	scores.
 
	Mostly the Fit method is used for Feature scaling
fit(X, y = None)


In [1]:
   
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
  
# Sklearn library  
from sklearn import preprocessing 
  
""" PART 2 
    Importing Data """
   
data_set = pd.read_csv('Data.csv') 
print("*******1st 5 rows of dataset********")
print(data_set.head() )

x = data_set.iloc[:, 1:3].values 
print ("\nOriginal data values : \n",  x) 
  
  
""" PART 4 
    Handling the missing values """
  
from sklearn import preprocessing 
  
""" MIN MAX SCALER """
  
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1)) 
  
# Scaled feature 
x_after_min_max_scaler = min_max_scaler.fit_transform(x) 
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler) 
  
  

*******1st 5 rows of dataset********
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
('\nOriginal data values : \n', array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01,     nan],
       [3.5e+01, 5.8e+04],
       [    nan, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]]))
('\nAfter min max Scaling : \n', array([[0.73913043, 0.68571429],
       [0.        , 0.        ],
       [0.13043478, 0.17142857],
       [0.47826087, 0.37142857],
       [0.56521739,        nan],
       [0.34782609, 0.28571429],
       [       nan, 0.11428571],
       [0.91304348, 0.88571429],
       [1.        , 1.        ],
       [0.43478261, 0.54285714]]))


In [2]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler 
# Read Data from CSV 
data = pd.read_csv('Data.csv')
x =data.iloc[:,1:3]
data.head() 
# Initialise the Scaler 
scaler = StandardScaler() 
# To scale data 
x =scaler.fit_transform(x) 


In [3]:
x

array([[ 0.71993143,  0.71101276],
       [-1.62367514, -1.36437583],
       [-1.21009751, -0.84552869],
       [-0.10722383, -0.24020701],
       [ 0.16849459,         nan],
       [-0.52080146, -0.49963059],
       [        nan, -1.01847774],
       [ 1.27136827,  1.31633443],
       [ 1.54708669,  1.66223253],
       [-0.24508304,  0.27864014]])